import {
  AccessTime,
  AutoFixHigh,
  CalendarMonth,
  ContentCut,
  Face,
  LocalOffer,
} from '@mui/icons-material';

import type { AnimatedBackgroundElement } from './AnimatedBackground.types';

export const DEFAULT_ANIMATED_BACKGROUND_ELEMENTS: AnimatedBackgroundElement[] = [
  {
    id: 'scissors-top-left',
    icon: ContentCut,
    top: '10%',
    left: '8%',
    size: 26,
    duration: 14,
    delay: 0,
    color: '#BF5AF2',
  },
  {
    id: 'calendar-top-left',
    icon: CalendarMonth,
    top: '23%',
    left: '28%',
    size: 22,
    duration: 16,
    delay: 1,
    color: '#0A84FF',
  },
  {
    id: 'magic-top-right',
    icon: AutoFixHigh,
    top: '16%',
    left: '70%',
    size: 20,
    duration: 15,
    delay: 2,
    color: '#64D2FF',
  },
  {
    id: 'clock-right',
    icon: AccessTime,
    top: '43%',
    left: '82%',
    size: 22,
    duration: 17,
    delay: 1,
    color: '#BF5AF2',
  },
  {
    id: 'face-left',
    icon: Face,
    top: '56%',
    left: '18%',
    size: 24,
    duration: 16,
    delay: 0,
    color: '#0A84FF',
  },
  {
    id: 'tag-center',
    icon: LocalOffer,
    top: '68%',
    left: '48%',
    size: 20,
    duration: 15,
    delay: 3,
    color: '#64D2FF',
  },
  {
    id: 'scissors-bottom-right',
    icon: ContentCut,
    top: '80%',
    left: '78%',
    size: 26,
    duration: 16,
    delay: 2,
    color: '#BF5AF2',
  },
];